#include <stdio.h>
#include <stdlib.h>

struct Panel {
    int id;
    double energy; 
};

int main() {
    FILE *fp;
    int n;
    struct Panel p;

    fp = fopen("solar_data.txt", "w");
    if (fp == NULL) {
        printf("Error opening file!\n");
        return 1;
    }

    printf("Enter number of solar panels: ");
    scanf("%d", &n);

    for (int i = 0; i < n; i++) {
        printf("\nEnter Panel %d ID: ", i + 1);
        scanf("%d", &p.id);

        printf("Enter Energy Generated by Panel %d (kWh): ", i + 1);
        scanf("%lf", &p.energy);

        fprintf(fp, "Panel ID: %d, Energy Generated: %.2lf kWh\n", p.id, p.energy);
    }

    fclose(fp);
    printf("\nData successfully written to solar_data.txt\n");

    return 0;
}
